version: '3.4'

services:
  crawler:
    image: crawler
    container_name: crawler_django
    command: ["gunicorn", "--bind", "0.0.0.0:8200", "app.wsgi:application"]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
    network_mode: host
    environment:
      DEBUG: 'True'
  
  redis:
    image: redis
    container_name: crawler_redis
    volumes: 
      - ./redis:/data
    restart: always
    network_mode: host
    # logging:
    #   driver: none
  
  celery_worker:
    image: crawler
    container_name: crawler_celery_worker
    volumes:
      - .:/app
    command: ["celery", "-A", "app", "worker", "-l", "info", "--pidfile="]
    restart: always
    network_mode: host
    logging:
      driver: none
  
  celery_scheduler:
    image: crawler
    container_name: crawler_celery_scheduler
    volumes:
      - .:/app
    command: ["celery", "-A", "app", "beat", "-l", "info", "--pidfile="]
    restart: always
    network_mode: host
    # logging:
    #   driver: none
  
  chrome_browser:
    image: selenium/standalone-chrome
    container_name: crawler_chrome_browser
    logging:
      driver: none
    restart: always
    network_mode: host
  
      